---
num_clients: 30 # total number of clients
num_epochs: 4 # number of local epochs
batch_size: 4
num_rounds: 35
clients_per_round: 15
learning_rate: 0.01
algorithm: fedper
algo: fedper

client_resources:
  num_cpus: 16
  num_gpus: 1

server_device: cuda:0

dataset:
  name : "flickr"
  iid: false
  num_classes: 5
  seed: 42
  num_clients: ${num_clients}
  split: 'sample' # sample or user
  fraction: 0.8

model:
  _target_: FedPer.models.mobile_model.MobileNet
  num_head_layers: 2
  num_classes: 5
  device: ${server_device}
  name: mobile

fit_config:
  drop_client: false
  epochs : ${num_epochs}
  batch_size: ${batch_size}

strategy:
  _target_: FedPer.utils.strategy_pipeline.AggregateBodyStrategyPipeline
  algorithm: ${algorithm}
  fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  min_fit_clients: ${num_clients}
  fraction_evaluate: 0.0
  min_evaluate_clients: ${num_clients}
  min_available_clients: ${num_clients}
  config: ${model}