[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quickstart-mlx"
version = "0.1.0"
description = "MLX Federated Learning Quickstart with Flower"
<<<<<<< HEAD
authors = ["The Flower Authors <hello@flower.dev>"]
=======
authors = ["The Flower Authors <hello@flower.ai>"]
>>>>>>> upstream/main

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = ">=1.0,<2.0"
mlx = "==0.0.3"
numpy = "==1.24.4"
<<<<<<< HEAD
flwr-datasets = {extras = ["vision"], version = "^0.0.2"}
=======
flwr-datasets = { extras = ["vision"], version = "^0.0.2" }
>>>>>>> upstream/main
