---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)
num_clients: 4 # total number of clients
num_epochs: 10 # number of local epochs
batch_size: 10
num_rounds: 5
clients_per_round: 3
learning_rate: 0.03

client_resources:
  num_cpus: 2
  num_gpus: 0.0

server_device: cpu

dataset:
  name : "cifar10"
  iid: false
  num_classes: 10

model:
  model: 'mobile'
  split: true
  num_head_layers: 1
  _target_: FedPer.models.MobileNet_v1
  num_classes: 10

strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config

client:
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_evaluate_clients: 0
  min_available_clients: ${clients_per_round}
  evaluate_metrics_aggregation_fn:
    _target_: fedprox.strategy.weighted_average
    _partial_: true # we dont' want this function to be evaluated when instantiating the strategy, we treat it as a partial and evaluate it when the strategy actuallly calls the function (in aggregate_evaluate())
