---
num_clients: 10 # total number of clients
num_epochs: 4 # number of local epochs
batch_size: 128
num_rounds: 50
clients_per_round: 10
learning_rate: 0.01
algorithm: fedavg
model_name: mobile

client_resources:
  num_cpus: 4
  num_gpus: 1

server_device: cuda:0

dataset:
  name : "cifar100"
  split: sample
  num_classes: 10
  seed: 42
  num_clients: ${num_clients}
  fraction: 0.83

model:
  _target_: fedPer.implemented_models.mobile_model.MobileNet
  num_head_layers: 2
  num_classes: 10

fit_config:
  drop_client: false
  epochs : ${num_epochs}
  batch_size: ${batch_size}

strategy:
  _target_: fedPer.server.DefaultStrategyPipeline
  fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  min_fit_clients: ${num_clients}
  fraction_evaluate: 0.0
  min_evaluate_clients: ${num_clients}
  min_available_clients: ${num_clients}
  algorithm: ${algorithm}
  evaluate_fn: None
  on_evaluate_config_fn: None