---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)
num_clients: 3
num_rounds: 15
num_epochs: 3
batch_size: 128
device: cuda:0
task: None
strategy_name: fedavg
learning_rate: 0.01
weight_decay: 0.00
model_name: resnet
centralized_eval: True
seed: 42

dataset:
  name: reg_cat_house_sales
  partition: linear
  id_col: None
  num_clients: ${num_clients}
  val_frac: 0.0
  num_input: 0
  num_classes: 0
  test_frac: 0.2

model:
  _target_: treesXnets.models.ResNet
  model_size: large  # small, medium, large (check in model file for more info)
  input_dim: ${dataset.num_input}
  output_dim: ${dataset.num_classes}
  task: ${task}
  batch_size: ${batch_size}
  n_channel: 1
  client_tree_num: 2
  num_clients: ${num_clients}


strategy:
  _target_: flwr.server.strategy.fedavg
  min_fit_clients: ${num_clients}
  min_evaluate_clients: ${num_clients}
  min_available_clients: ${num_clients}
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  evaluate_fn: None
  on_evaluate_config_fn: 
    _target_: treesXnets.strategy.get_evaluate_config

client_fn:
  _target_: treesXnets.client.get_client_fn
  _recursive_: False

client: 
  batch_size: ${batch_size}
  task: ${task}
  dataset_name: ${dataset.name}
  strategy_name: ${strategy_name}
  lr: ${learning_rate}
  wd: ${weight_decay}
  device: ${device}
  num_epochs: ${num_epochs}
  num_local_round: 4
  client_tree_num: 3
  num_clients: ${num_clients}

client_resources:
  num_cpus: 16
  num_gpus: 1
