---
num_clients: 10 # total number of clients
num_epochs: 4 # number of local epochs
batch_size: 128
num_rounds: 100
clients_per_round: 3
learning_rate: 0.01
algorithm: fedavg
algo: fedavg
global_testset: False

client_resources:
  num_cpus: 16
  num_gpus: 1

server_device: cuda:0

dataset:
  name : "cifar10"
  iid: false
  num_classes: 4
  classes_per_client: 4
  seed: 42
  split: 'sample' # sample, user
  num_clients: ${num_clients}
  fraction: 0.83

model:
  _target_: FedPer.model.resnet_model.ResNet
  num_classifier_layers: 2
  num_classes: 10
  device: ${server_device}
  name: resnet
  dataset: ${dataset.name}

fit_config:
  drop_client: false
  epochs : ${num_epochs}
  batch_size: ${batch_size}

strategy:
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 1.0 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  min_fit_clients: ${num_clients}
  fraction_evaluate: 1.0
  min_evaluate_clients: ${num_clients}
  min_available_clients: ${num_clients}
  config: ${model}
  evaluate_metrics_aggregation_fn:
    _target_: FedPer_new.utils.weighted_average